package org.vis.mcpserver.entity;

import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

@Table(name = "seller_account")
public class SellerAccount {
    @Id
    @Column
    private Long id;

    private String name;

    private String owner;

    private Boolean isTest;

    private String type;
    private Integer status;

    /**
     * Get Seller Account ID
     * Method Name: getId
     * Parameters: None
     * Return Type: Long - The unique identifier for the seller account
     *
     * Usage: Returns the primary key ID of the seller account.
     * This ID is auto-generated by the database as BIGSERIAL and uniquely identifies
     * each seller account record in the seller_account table.
     */
    public Long getId() {
        return id;
    }

    /**
     * Get Seller Account Name
     * Method Name: getName
     * Parameters: None
     * Return Type: String - The name of the seller account
     *
     * Usage: Returns the name of the seller account. This is a required field (NOT NULL)
     * that represents the business or account name. Used for searching and identifying
     * sellers. Max length: 255 characters.
     */
    public String getName() {
        return name;
    }

    /**
     * Get Seller Account Owner
     * Method Name: getOwner
     * Parameters: None
     * Return Type: String - The owner/organization of the seller account
     *
     * Usage: Returns the name of the owner or parent organization managing this seller account.
     * Examples: "amazon", "flipkart", "manomano". This field can be null and is used
     * to identify which marketplace or organization owns the seller account.
     */
    public String getOwner() {
        return owner;
    }

    /**
     * Get Seller Account Test Status
     * Method Name: getTest
     * Parameters: None
     * Return Type: Boolean - Whether this is a test account
     *
     * Usage: Returns whether this seller account is a test/development account (true)
     * or a production account (false). Defaults to FALSE in the database.
     * Useful for distinguishing between real and test sellers.
     */
    public Boolean getTest() {
        return isTest;
    }

    /**
     * Get Seller Account Type
     * Method Name: getType
     * Parameters: None
     * Return Type: String - The type/category of the seller account
     *
     * Usage: Returns the account type classification. Common values include "STD" (Standard).
     * This categorizes sellers by their account tier or type. Can be null.
     * Examples: "STD", "PREMIUM", "ENTERPRISE". Max length: 255 characters.
     */
    public String getType() {
        return type;
    }

    /**
     * Get Seller Account Status
     * Method Name: getStatus
     * Parameters: None
     * Return Type: Integer - The status code of the seller account
     *
     * Usage: Returns the numeric status code representing the account state.
     * Common values: 1 (ACTIVE), 0 (INACTIVE), -1 (SUSPENDED).
     * This is a required field (NOT NULL) that indicates the operational status
     * of the seller account.
     */
    public Integer getStatus() {
        return status;
    }
}
